### ISSUE TITLE
Bug after restoration

### ISSUE THREAD

**Issue by Refhi** [nextcloud/mail#1041]
### Actual behavior
after restoration (snap version), when opening "mail" get "Error: An unkown error occurred." and folders & mails of mail accounts not showing.
Everything fine after manually reconfiguring the mail accounts.
 

### Mail app

**Mail app version:**   - mail: 0.8.3

**Mailserver or service:** any

**Number of accounts:** 1 to 3

### Server configuration

**Operating system**: ubuntu 16 LTS & 18 LTS (tried on both)

**Nextcloud Version:** 13.0.5snap1

**Updated from an older version or fresh install:** restored

**List of activated apps:**
```
Enabled:
  - activity: 2.6.1
  - admin_notifications: 1.0.1
  - apporder: 0.5.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - deck: 0.4.1
  - external: 3.0.4
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - impersonate: 1.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.8.3
  - news: 12.0.4
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - passwords: 2018.7.0
  - polls: 0.8.1
  - previewgenerator: 1.1.0
  - provisioning_api: 1.3.0
  - radio: 0.6.1
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.5
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - user_external: 0.4
  - weather: 1.5.1
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_videoplayer
  - user_ldap
```

**The content of config/config.php:**
```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.56",
            "mathieudevienne.fr",
            "drbr.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/192.168.0.56",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "data-fingerprint": "6811e6dec3a2133a04d84c7145275d4a"
    }
}

```

#### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 61
**Operating system:** (e.g. Arch Linux)
Ubuntu gnome

##### Server log (data/nextcloud.log)
```
{"reqId":"yxltgI7ao1DlnxUv81HT","level":3,"time":"2018-08-18T21:12:17+00:00","remoteAddr":"77.205.87.198","user":"admin","app":"lib","method":"GET","url":"\/index.php\/apps\/mail\/","message":"ResourceLocator can not find a web root (root: \/var\/snap\/nextcloud\/8267\/nextcloud\/extra-apps\/mail, file: index.php\/css\/mail\/c5f3-a446-mail.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.5.2"}
{"reqId":"P4uN61DEXPr7834YBeSC","level":3,"time":"2018-08-18T21:12:19+00:00","remoteAddr":"77.205.87.198","user":"admin","app":"mail","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/13\/folders","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"HMAC does not match.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/snap\\\/nextcloud\\\/8267\\\/nextcloud\\\/extra-apps\\\/mail\\\/lib\\\/IMAP\\\/IMAPClientFactory.php(61): OC\\\\Security\\\\Crypto->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/var\\\/snap\\\/nextcloud\\\/8267\\\/nextcloud\\\/extra-apps\\\/mail\\\/lib\\\/Service\\\/MailManager.php(82): OCA\\\\Mail\\\\IMAP\\\\IMAPClientFactory->getClient(Object(OCA\\\\Mail\\\\Account))\\n#2 \\\/var\\\/snap\\\/nextcloud\\\/8267\\\/nextcloud\\\/extra-apps\\\/mail\\\/lib\\\/Controller\\\/FoldersController.php(72): OCA\\\\Mail\\\\Service\\\\MailManager->getFolders(Object(OCA\\\\Mail\\\\Account))\\n#3 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index(13)\\n#4 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#5 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#6 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#7 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Mail\\\\\\\\Contro...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/api\\\/...')\\n#11 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/index.php(42): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/Security\\\/Crypto.php\",\"Line\":129}","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.5.2"}

```

**Comment by ChristophWurst** [comment]
> HMAC does not match.

Sounds like you restored a database that does not match the `secret` in `config.php`, hence the decryption fails.

This is a setup issue, unrelated to this app. Have a look at https://help.nextcloud.com/ for similar questions.
