### ISSUE TITLE
Links in mails not working anymore

### ISSUE THREAD

**Issue by Patta** [nextcloud/mail#1341]
### Steps to reproduce
Setup Mail Account and click on link in received mail.

### Expected behaviour
The link is resolved to target.

(Worked in 14.0.3)

### Actual behaviour
A internal server error message is shown.

With enabled debugging:
```
Interner Serverfehler
Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.

Technische Details
Entfernte Adresse: 2003:a:228:cf00:7d02:88c:b36a:b6fa
Anfragekennung: W-0M7VkWZHUAACqZqb8AAAAE
Typ: TypeError
Code: 0
Nachricht: Argument 1 passed to OCA\Mail\Controller\ProxyController::redirect() must be of the type string, null given, called in /var/www/vhosts/REMOVED/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 166
Datei: /var/www/vhosts/REMOVED/nextcloud/apps/mail/lib/Controller/ProxyController.php
Zeile: 83

Trace
#0 /var/www/vhosts/REMOVED/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(166): OCA\Mail\Controller\ProxyController->redirect(NULL)
#1 /var/www/vhosts/REMOVED/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(99): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\ProxyController), 'redirect')
#2 /var/www/vhosts/REMOVED/nextcloud/lib/private/AppFramework/App.php(118): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\ProxyController), 'redirect')
#3 /var/www/vhosts/REMOVED/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Mail\\Contro...', 'redirect', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#4 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#5 /var/www/vhosts/REMOVED/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#6 /var/www/vhosts/REMOVED/nextcloud/lib/base.php(987): OC\Route\Router->match('/apps/mail/redi...')
#7 /var/www/vhosts/REMOVED/nextcloud/index.php(42): OC::handleRequest()
#8 {main}
```

## Server configuration detail

**Operating system:** Linux 3.16.0-042stab128.2 #1 SMP Wed Jul 11 13:51:30 MSK 2018 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.0.37

**PHP version:** 

7.2.12
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 14.0.4 - 14.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - apporder: 0.6.0
 - bruteforcesettings: 1.2.0
 - calendar: 1.6.4
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.7
 - dav: 1.6.0
 - deck: 0.5.0
 - encryption: 2.2.0
 - end_to_end_encryption: 1.0.5
 - federatedfilesharing: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - mail: 0.11.0
 - news: 13.0.3
 - nextcloud_announcements: 1.3.0
 - notes: 2.5.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - ransomware_protection: 1.2.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - twofactor_totp: 1.5.0
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - activity
 - admin_audit
 - audioplayer
 - federation
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "debug": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "14.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 4,
    "appstore.experimental.enabled": true,
    "maintenance": false,
    "theme": "",
    "mysql.utf8mb4": true,
    "mail_smtpauthtype": "LOGIN",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

**Operating system:** Windows 10 1803

## Logs

<details><summary>Browser log</summary>

```
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.0
shareconfigmodel.js:24 Uncaught ReferenceError: oc_appconfig is not defined
    at shareconfigmodel.js:24
    at shareconfigmodel.js:80
js.js:209 Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.filePath (js.js:209)
    at viewer.js:15
```
</details>

<details><summary>Nextcloud log</summary>

```
no new entry
```
</details>

<details><summary>Browser log</summary>

jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.0
shareconfigmodel.js:24 Uncaught ReferenceError: oc_appconfig is not defined
    at shareconfigmodel.js:24
    at shareconfigmodel.js:80
js.js:209 Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.filePath (js.js:209)
    at viewer.js:15
</details>

**Comment by ChristophWurst** [comment]
Did your session expire? Were you logged out for some reason?

**Comment by Patta** [comment]
@ChristophWurst no. i tried log off and in again. but still the issue.

**Comment by Patta** [comment]
I fixed it by disabled the nginxProxyMode in plesk onyx 17.8.
