### ISSUE TITLE
Can not delete Gmail messages

### ISSUE THREAD

**Issue by koarlmichael** [nextcloud/mail#136]
### Steps to reproduce

When I use Gmail in the mail app everything works fine. But if I want to delete a message ist comes the error "Fehler beim Löschen der Nachricht." 
### Expected behaviour

Delete should work
### Actual behaviour

The message can not be deleted and appears again and again.
### Mail app

Mail 0.5.3

Gmail Settings:

imap.gmail.com

Requires SSL: Yes

Port: 993

smtp.gmail.com

Requires SSL: Yes

Requires Authentication: Yes

Port for SSL: 465
### Server configuration

**Operating system**:
Debian Jessie
**Web server:**
apache2 (2.4.10-10+deb8u7)
**Database:**
Type: mysql
Version: 5.5.52
**PHP version:**
Version 7.0.11

**Updated from an older version or fresh install:**
Update from 10.0.0
**List of activated apps:**
Enabled:
- activity: 2.3.2
- admin_audit: 1.0.0
- calendar: 1.4.0
- comments: 1.0.0
- contacts: 1.4.0.0
- dav: 1.0.1
- external: 1.2
- federatedfilesharing: 1.0.1
- federation: 1.0.1
- files: 1.5.2
- files_accesscontrol: 1.1.2
- files_external: 1.0.2
- files_pdfviewer: 0.8.1
- files_sharing: 1.0.0
- files_texteditor: 2.1
- files_trashbin: 1.0.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 15.0.0
- mail: 0.5.3
- news: 9.0.4
- notifications: 0.3.0
- ownbackup: 0.3.8
- password_policy: 1.0.0
- provisioning_api: 1.0.0
- richdocuments: 1.1.7
- serverinfo: 1.1.1
- survey_client: 0.1.5
- systemtags: 1.0.2
- templateeditor: 0.1
- theming: 1.0.1
- updatenotification: 1.0.1
- workflowengine: 1.0.1
  Disabled:
- encryption
- files_automatedtagging
- files_retention
- user_external
- user_ldap
- user_saml

**The content of config/config.php:**

{
    "system": {
        "updatechecker": false,
        "instanceid": "**_REMOVED SENSITIVE VALUE**_",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "**_REMOVED SENSITIVE VALUE**_",
            "**_REMOVED SENSITIVE VALUE**_"
        ],
        "datadirectory": "\/srv\/data",
        "overwrite.cli.url": "https:\/\/**_REMOVED SENSITIVE VALUE**_\/nextcloud",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "logfile": "\/srv\/data\/nextcloud.log",
        "loglevel": 1,
        "memcache.local": "\OC\Memcache\Redis",
        "memcache.locking": "\OC\Memcache\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "theme": "",
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "log_rotate_size": 10485760,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "**_REMOVED SENSITIVE VALUE**_",
        "mail_domain": "gmail.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "587",
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "logging"
        },
        "announcementcenter": {
            "enabled": "no",
            "installed_version": "0",
            "ocsid": "173921",
            "signed": "true",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "12"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.4.0.0",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "OC_Channel": "stable",
            "backgroundjobs_mode": "cron",
            "incoming_server2server_share_enabled": "no",
            "installedat": "1458458097.0455",
            "lastcron": "1475759224",
            "lastupdateResult": "[]",
            "lastupdatedat": "1475758758",
            "oc.integritycheck.checker": "[]",
            "outgoing_server2server_share_enabled": "no",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_richdocuments": "richdocuments\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_default_expire_date": "yes",
            "shareapi_expire_after_n_days": "18",
            "umgmt_show_email": "true",
            "umgmt_show_last_login": "true",
            "umgmt_show_storage_location": "false",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "documents": {
            "converter": "local",
            "enabled": "no",
            "installed_version": "0.12.0",
            "ocsid": "168711",
            "types": ""
        },
        "external": {
            "enabled": "yes",
            "installed_version": "1.2",
            "ocsid": "166046",
            "sites": "**_REMOVED SENSITIVE VALUE**_,
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "federation": {
            "autoAddServers": "0",
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "5 GB",
            "enabled": "yes",
            "installed_version": "1.5.2",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.0.2",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "yes",
            "installed_version": "1.0.0",
            "outgoing_server2server_share_enabled": "yes",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "15.0.0",
            "types": ""
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "0.5.3",
            "ocsid": "169914",
            "signed": "true",
            "types": ""
        },
        "news": {
            "enabled": "yes",
            "installed_version": "9.0.4",
            "ocsid": "168040",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "ojsxc": {
            "enabled": "no",
            "installed_version": "3.0.0",
            "ocsid": "162257",
            "types": "prelogin"
        },
        "ownbackup": {
            "enabled": "yes",
            "installed_version": "0.3.8",
            "ocsid": "170674",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "minLength": "10",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "prevent_group_restriction"
        },
        "richdocuments": {
            "enabled": "yes",
            "installed_version": "1.1.7",
            "ocsid": "174727",
            "types": "",
            "wopi_url": "https:\/\/**_REMOVED SENSITIVE VALUE**_"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "shorten": {
            "enabled": "no",
            "installed_version": "0.0.15",
            "ocsid": "168591",
            "types": "filesystem"
        },
        "spreedme": {
            "OWNCLOUD_TEMPORARY_PASSWORD_LOGIN_ENABLED": "false",
            "SPREED_WEBRTC_BASEPATH": "\/webrtc\/",
            "SPREED_WEBRTC_IS_SHARED_INSTANCE": "false",
            "SPREED_WEBRTC_ORIGIN": "",
            "enabled": "no",
            "installed_version": "0.3.1",
            "is_set_up": "true",
            "ocsid": "174436",
            "types": ""
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.0.2",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "theming": {
            "backgroundMime": "image\/jpeg",
            "cachebuster": "114",
            "color": "#004E78",
            "enabled": "yes",
            "installed_version": "1.0.1",
            "logoMime": "image\/svg+xml",
            "name": "****",
            "types": "logging"
        },
        "updatenotification": {
            "calendar": "1.4.0",
            "contacts": "1.4.0.0",
            "enabled": "yes",
            "installed_version": "1.0.1",
            "mail": "0.5.3",
            "news": "9.0.4",
            "richdocuments": "1.1.7",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        }
    }
}
#### Client configuration

**Browser:**
Chromium 53.0.2785.113 built on Debian stretch/sid,
Google Chrome on macOS Sierra
**Operating system:**
Debian Stretch and macOS Sierra
##### Server log (data/nextcloud.log)

<details>

```
Exception: {"Exception":"Horde_Imap_Client_Exception_ServerResponse","Message":"The object could not be created because it already exists.","Code":22,"Trace":"#0 \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4554): Horde_Imap_Client_Socket->responseCode(Object(HordeImap_Client_Interaction_Pipeline), Object(Horde_Imap_Client_Interaction_Server_Tagged))\n#1 \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4302): Horde_Imap_Client_Socket->getLine(Object(HordeImap_Client_Interaction_Pipeline))\n#2 \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4230): Horde_Imap_Client_Socket->sendCmdChunk(Object(HordeImap_Client_Interaction_Pipeline), Array)\n#3 \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(1271): Horde_Imap_Client_Socket->sendCmd(Object(HordeImap_Client_Interaction_Command))\n#4 \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Base.php(1141): Horde_Imap_Client_Socket->createMailbox(Object(HordeImap_Client_Mailbox), Array)\n#5 \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(3682): Horde_Imap_Client_Base->createMailbox(Object(Horde_Imap_Client_Mailbox))\n#6 \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Base.php(2955): Horde_Imap_Client_Socket->copy(Object(HordeImap_Client_Mailbox), Array)\n#7 \/var\/www\/nextcloud\/apps\/mail\/lib\/account.php(499): Horde_Imap_Client_Base->copy(Object(Horde_Imap_Client_Mailbox), Object(Horde_Imap_Client_Mailbox), Array)\n#8 \/var\/www\/nextcloud\/apps\/mail\/lib\/controller\/messagescontroller.php(350): OCA\Mail\Account->deleteMessage('INBOX', '16686')\n#9 [internal function]: OCA\Mail\Controller\MessagesController->destroy(5, 'SU5CT1g=', '16686')\n#10 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#11 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\MessagesController), 'destroy')\n#12 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(111): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\MessagesController), 'destroy')\n#13 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Mail\\Contro...', 'destroy', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#14 [internal function]: OC\AppFramework\Routing\RouteActionHandler->_invoke(Array)\n#15 \/var\/www\/nextcloud\/lib\/private\/Route\/Router.php(293): calluser_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)\n#16 \/var\/www\/nextcloud\/lib\/base.php(983): OC\Route\Router->match('\/apps\/mail\/acco...')\n#17 \/var\/www\/nextcloud\/index.php(48): OC::handleRequest()\n#18 {main}","File":"\/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php","Line":5109}


```

</details>

**Comment by koarlmichael** [comment]
Delete all previous IMAP Labels in Gmail Web and then it worked.
