### ISSUE TITLE
Opening mail fails with: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by IchbinkeinReh** [nextcloud/mail#3693]
### Expected behavior
Mail is displayed correctly and no js error occurs

### Actual behavior
When i opened a mail i got the following js error and the email is not displayed.

mail.js:formatted:5776 DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at a.threadingFile (https://ichbinkeinreh.de/cloud/apps/mail/js/mail.js:530:173675)
    at fn.get (https://ichbinkeinreh.de/cloud/apps/mail/js/mail.js:36:26610)
    at fn.evaluate (https://ichbinkeinreh.de/cloud/apps/mail/js/mail.js:36:27760)
    at a.threadingFile (https://ichbinkeinreh.de/cloud/apps/mail/js/mail.js:36:29669)
    at a.r (https://ichbinkeinreh.de/cloud/apps/mail/js/mail.js:813:2867)
    at a.e._render (https://ichbinkeinreh.de/cloud/apps/mail/js/mail.js:36:35296)
    at a.r (https://ichbinkeinreh.de/cloud/apps/mail/js/mail.js:36:64441)
    at fn.get (https://ichbinkeinreh.de/cloud/apps/mail/js/mail.js:36:26610)
    at new fn (https://ichbinkeinreh.de/cloud/apps/mail/js/mail.js:36:26528)
    at e (https://ichbinkeinreh.de/cloud/apps/mail/js/mail.js:36:64455)

### Mail app

**Mail app version:** v1.5.0

**Mailserver or service:** Strato

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 20.0.0

#### Client configuration
**Browser:** Chrome 81

**Operating system:** Ubuntu 20.04

**Comment by StCyr** [comment]
I guess it's the same as mine https://github.com/nextcloud/mail/issues/3691 with a little bit more info
