### ISSUE TITLE
Upgrade to v1.9.2: Call to undefined method OCA\Mail\Db\MessageMapper::findWithEmptyMessageId() 

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#4746]
### Expected behavior

Upgrade to v1.9.2 runs smooth.

### Actual behavior

```
mail new version available: 1.9.2
An unhandled exception has been thrown:
Error: Call to undefined method OCA\Mail\Db\MessageMapper::findWithEmptyMessageId() in /var/www/html/apps/mail/lib/Migration/AddMissingMessageIds.php:55
Stack trace:
#0 /var/www/html/lib/private/Repair.php(117): OCA\Mail\Migration\AddMissingMessageIds->run()
#1 /var/www/html/lib/private/legacy/OC_App.php(1054): OC\Repair->run()
#2 /var/www/html/lib/private/legacy/OC_App.php(996): OC_App::executeRepairSteps()
#3 /var/www/html/lib/private/Installer.php(212): OC_App::updateApp()
#4 /var/www/html/core/Command/App/Update.php(116): OC\Installer->updateAppstoreApp()
#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Update->execute()
#6 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#7 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#9 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#10 /var/www/html/console.php(100): OC\Console\Application->run()
#11 /var/www/html/occ(11): require_once('/var/www/html/c...')
#12 {main}
```

This is most likely the same problem as https://github.com/nextcloud/mail/issues/3727. The upgrade is performed and the app code is replaced. Then we load the new repair step that uses a previously known class, but with changed code. Hence the method doesn't exist.

### Mail app

**Mail app version:** v1.9.2

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/mail/pull/4747
