### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/mail#4766]
### Expected behavior
I can open Mail application

### Actual behavior
I can't open, get Internal Server Error
In logs I see

```
{
	"reqId": "4nH23fMuEBiVmqU53fKI",
	"level": 3,
	"time": "2021-03-15T14:44:29+01:00",
	"remoteAddr": "46.28.104.66",
	"user": "user",
	"app": "index",
	"method": "GET",
	"url": "/apps/mail/",
	"message": {
		"Exception": "Exception",
		"Message": "explode() expects parameter 1 to be string, null given",
		"Code": 0,
		"Trace": [
			{
				"file": "/var/www/html/lib/private/AppFramework/App.php",
				"line": 137,
				"function": "dispatch",
				"class": "OC\\AppFramework\\Http\\Dispatcher",
				"type": "->",
				"args": [
					{
						"__class__": "OCA\\Mail\\Controller\\PageController"
					},
					"index"
				]
			},
			{
				"file": "/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php",
				"line": 47,
				"function": "main",
				"class": "OC\\AppFramework\\App",
				"type": "::",
				"args": [
					"OCA\\Mail\\Controller\\PageController",
					"index",
					{
						"__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
					},
					{
						"_route": "mail.page.index"
					}
				]
			},
			{
				"function": "__invoke",
				"class": "OC\\AppFramework\\Routing\\RouteActionHandler",
				"type": "->",
				"args": [
					{
						"_route": "mail.page.index"
					}
				]
			},
			{
				"file": "/var/www/html/lib/private/Route/Router.php",
				"line": 297,
				"function": "call_user_func",
				"args": [
					{
						"__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
					},
					{
						"_route": "mail.page.index"
					}
				]
			},
			{
				"file": "/var/www/html/lib/base.php",
				"line": 1007,
				"function": "match",
				"class": "OC\\Route\\Router",
				"type": "->",
				"args": [
					"/apps/mail/"
				]
			},
			{
				"file": "/var/www/html/index.php",
				"line": 37,
				"function": "handleRequest",
				"class": "OC",
				"type": "::",
				"args": []
			}
		],
		"File": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
		"Line": 110,
		"Previous": {
			"Exception": "TypeError",
			"Message": "explode() expects parameter 1 to be string, null given",
			"Code": 0,
			"Trace": [
				{
					"file": "/var/www/html/apps/mail/lib/IMAP/FolderMapper.php",
					"line": 214,
					"function": "explode",
					"args": [
						null,
						"INBOX",
						2
					]
				},
				{
					"file": "/var/www/html/apps/mail/lib/IMAP/FolderMapper.php",
					"line": 193,
					"function": "guessSpecialUse",
					"class": "OCA\\Mail\\IMAP\\FolderMapper",
					"type": "->",
					"args": [
						{
							"__class__": "OCA\\Mail\\Folder"
						}
					]
				},
				{
					"file": "/var/www/html/apps/mail/lib/IMAP/FolderMapper.php",
					"line": 149,
					"function": "detectSpecialUse",
					"class": "OCA\\Mail\\IMAP\\FolderMapper",
					"type": "->",
					"args": [
						{
							"__class__": "OCA\\Mail\\Folder"
						}
					]
				},
				{
					"file": "/var/www/html/apps/mail/lib/IMAP/MailboxSync.php",
					"line": 90,
					"function": "detectFolderSpecialUse",
					"class": "OCA\\Mail\\IMAP\\FolderMapper",
					"type": "->",
					"args": [
						{
							"INBOX": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"sent": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"drafts": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"newsletters": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"archive": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"spam": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"trash": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"Fohat": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"Kubálek": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"Notes": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"pojišťovny": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"Pavla": {
								"__class__": "OCA\\Mail\\Folder"
							},
							"Scan": {
								"__class__": "OCA\\Mail\\Folder"
							}
						}
					]
				},
				{
					"file": "/var/www/html/apps/mail/lib/Service/MailManager.php",
					"line": 101,
					"function": "sync",
					"class": "OCA\\Mail\\IMAP\\MailboxSync",
					"type": "->",
					"args": [
						{
							"__class__": "OCA\\Mail\\Account"
						}
					]
				},
				{
					"file": "/var/www/html/apps/mail/lib/Controller/PageController.php",
					"line": 119,
					"function": "getFolders",
					"class": "OCA\\Mail\\Service\\MailManager",
					"type": "->",
					"args": [
						{
							"__class__": "OCA\\Mail\\Account"
						}
					]
				},
				{
					"file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
					"line": 170,
					"function": "index",
					"class": "OCA\\Mail\\Controller\\PageController",
					"type": "->",
					"args": []
				},
				{
					"file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
					"line": 100,
					"function": "executeController",
					"class": "OC\\AppFramework\\Http\\Dispatcher",
					"type": "->",
					"args": [
						{
							"__class__": "OCA\\Mail\\Controller\\PageController"
						},
						"index"
					]
				},
				{
					"file": "/var/www/html/lib/private/AppFramework/App.php",
					"line": 137,
					"function": "dispatch",
					"class": "OC\\AppFramework\\Http\\Dispatcher",
					"type": "->",
					"args": [
						{
							"__class__": "OCA\\Mail\\Controller\\PageController"
						},
						"index"
					]
				},
				{
					"file": "/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php",
					"line": 47,
					"function": "main",
					"class": "OC\\AppFramework\\App",
					"type": "::",
					"args": [
						"OCA\\Mail\\Controller\\PageController",
						"index",
						{
							"__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
						},
						{
							"_route": "mail.page.index"
						}
					]
				},
				{
					"function": "__invoke",
					"class": "OC\\AppFramework\\Routing\\RouteActionHandler",
					"type": "->",
					"args": [
						{
							"_route": "mail.page.index"
						}
					]
				},
				{
					"file": "/var/www/html/lib/private/Route/Router.php",
					"line": 297,
					"function": "call_user_func",
					"args": [
						{
							"__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
						},
						{
							"_route": "mail.page.index"
						}
					]
				},
				{
					"file": "/var/www/html/lib/base.php",
					"line": 1007,
					"function": "match",
					"class": "OC\\Route\\Router",
					"type": "->",
					"args": [
						"/apps/mail/"
					]
				},
				{
					"file": "/var/www/html/index.php",
					"line": 37,
					"function": "handleRequest",
					"class": "OC",
					"type": "::",
					"args": []
				}
			],
			"File": "/var/www/html/apps/mail/lib/IMAP/FolderMapper.php",
			"Line": 214
		},
		"CustomMessage": "--"
	},
	"userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0",
	"version": "19.0.1.1"
}
```

In `occ mail:account:diagnose`
```
root@nextcloud-2:/var/www/html# sudo -u www-data php occ mail:account:diagnose 228                                                                                                             
IMAP capabilities:                                                                                                                                                      
- CHILDREN                                                                                                                              
- I18NLEVEL                                                                                                                                 
- IMAP4REV1                                                                                                                                 
- SORT                                                                                                                  
- STARTTLS                                                                                                                              
- UIDPLUS                                                                                                                           
- XLIST    
```

In `occ mail:account:sync` I have
```
root@nextcloud-2:/var/www/html# sudo -u www-data php occ mail:account:sync 228
An unhandled exception has been thrown:
TypeError: explode() expects parameter 1 to be string, null given in /var/www/html/apps/mail/lib/IMAP/FolderMapper.php:214
Stack trace:
#0 /var/www/html/apps/mail/lib/IMAP/FolderMapper.php(214): explode(NULL, 'INBOX', 2)
#1 /var/www/html/apps/mail/lib/IMAP/FolderMapper.php(193): OCA\Mail\IMAP\FolderMapper->guessSpecialUse(Object(OCA\Mail\Folder))
#2 /var/www/html/apps/mail/lib/IMAP/FolderMapper.php(149): OCA\Mail\IMAP\FolderMapper->detectSpecialUse(Object(OCA\Mail\Folder))
#3 /var/www/html/apps/mail/lib/IMAP/MailboxSync.php(90): OCA\Mail\IMAP\FolderMapper->detectFolderSpecialUse(Array)
#4 /var/www/html/apps/mail/lib/Command/SyncAccount.php(91): OCA\Mail\IMAP\MailboxSync->sync(Object(OCA\Mail\Account), false)
#5 /var/www/html/apps/mail/lib/Command/SyncAccount.php(83): OCA\Mail\Command\SyncAccount->sync(Object(OCA\Mail\Account), false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Mail\Command\SyncAccount->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Mail\Command\SyncAccount), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/console.php(100): OC\Console\Application->run()
#12 /var/www/html/occ(11): require_once('/var/www/html/c...')
#13 {main}
```

### Mail app

**Mail app version:** (see apps admin page, e.g. 0.5.3)
1.4.3

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
seznam.cz

### Server configuration

**Operating system**: (e.g. Debian 8)
Linux 4.15.18-28-pve #1 SMP PVE 4.15.18-56 (Wed, 08 Apr 2020 20:06:11 +0200) x86_64

**Web server:** (e.g. Apache, Nginx,...)
nginx/1.19.7 (fpm-fcgi)

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
mysql 5.7.18

**PHP version:** (e.g. 7.0)
7.4.14
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud Version:** (see admin page, e.g. 13.0.2)
19.0.1

**Comment by ChristophWurst** [comment]
Thanks for the report @krakazyabra.

THis sounds like a dup of https://github.com/nextcloud/mail/issues/2105
