### ISSUE TITLE
Error: Class '\OCA\User_LDAP\LDAPProviderFactory' after upgrade to 1.11.0

### ISSUE THREAD

**Issue by geosphere** [nextcloud/mail#5778]
### Expected behavior
upgraded Mail app to 1.11.0

### Actual behavior  
App upgrade does not complete successfully, application remains disabled.
After trying to enable, I get the following log:

```
/ # occ app:enable mail
An unhandled exception has been thrown:
Error: Class '\OCA\User_LDAP\LDAPProviderFactory' not found in /nextcloud/lib/private/Server.php:1029
Stack trace:
#0 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
#1 /nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#2 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\\LDAP\\ILDAPP...')
#3 /nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\\LDAP\\ILDAPP...', false)
#4 /nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(434): OC\ServerContainer->query('OCP\\LDAP\\ILDAPP...', true)
#5 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query('OCP\\LDAP\\ILDAPP...', true)
#6 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#7 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map(Object(Closure), Array)
#8 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#9 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Mail\\Servic...')
#10 /nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Mail\\Servic...')
#11 /nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(431): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Mail\\Servic...')
#12 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Mail\\Servic...', true)
#13 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#14 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map(Object(Closure), Array)
#15 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#16 /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Mail\\Migrat...')
#17 /nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Mail\\Migrat...')
#18 /nextcloud/lib/private/ServerContainer.php(146): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Mail\\Migrat...')
#19 /nextcloud/lib/private/Repair.php(131): OC\ServerContainer->query('OCA\\Mail\\Migrat...')
#20 /nextcloud/lib/private/legacy/OC_App.php(1066): OC\Repair->addStep('OCA\\Mail\\Migrat...')
#21 /nextcloud/lib/private/Installer.php(165): OC_App::executeRepairSteps('mail', Array)
#22 /nextcloud/core/Command/App/Enable.php(123): OC\Installer->installApp('mail', false)
#23 /nextcloud/core/Command/App/Enable.php(93): OC\Core\Command\App\Enable->enableApp('mail', Array, false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /nextcloud/console.php(100): OC\Console\Application->run()
#30 /nextcloud/occ(11): require_once('/nextcloud/cons...')
#31 {main}/ # 
```
Full deinstall and fresh install does not fix the issue.

### Mail app

**Mail app version:**  1.11.0

**Mailserver or service:** several different

### Server configuration

**Operating system**:  Docker based on Alpine 3.13~3.15

**Web server:** Nginx, 

**Database:** PostgreSQL

**PHP version:**  php-fpm 7.4.26

**Nextcloud Version:** 21.0.5~21.0.7

**Comment by ChristophWurst** [comment]
See https://help.nextcloud.com/t/error-on-upgrading-nextcloud/128281
