### ISSUE TITLE
Nextcloud stuck in maintenance mode after upgrade from 1.12.1 to 1.13.0

### ISSUE THREAD

**Issue by patzm** [nextcloud/mail#6630]
### Steps to reproduce

1. Have a NextCloud 24.0.0 instance
2. Have a Mail [`v1.12.1`](https://github.com/nextcloud/mail/releases/tag/v1.12.1) installation
3. upgrade through the UI to [`v1.13.0`](https://github.com/nextcloud/mail/releases/tag/v1.13.0)

### Expected behavior

After the update, everything runs again

### Actual behavior

The instance is stuck in maintenance mode:
![image](https://user-images.githubusercontent.com/5219726/171627819-a54c7f0c-10d8-4846-be95-8b695a48b9ba.png)

### Mail app version

v1.12.1

### Mailserver or service

-

### Operating system

docker in TrueNas Scale (Linux)

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database

MariaDB

### Additional info

PHP, WebServer and Database are those of the docker image, which is https://hub.docker.com/layers/nextcloud/crazymax/nextcloud/24.0.0/images/sha256-584c2602067e1164f958b8ca05709b05feed41038afc74b4040b01589d2eefd2?context=explore
So specifically:
* `php8`: https://hub.docker.com/layers/nextcloud/crazymax/nextcloud/24.0.0/images/sha256-584c2602067e1164f958b8ca05709b05feed41038afc74b4040b01589d2eefd2?context=explore, which is currently `8.0.19r1` ([source](https://pkgs.alpinelinux.org/package/edge/community/x86_64/php8))
* `nginx`: https://github.com/crazy-max/docker-nextcloud/blob/6a01ea77c45b884a54c01160f25e04e8f3030503/Dockerfile-24#L30, which is currently [`1.22.0-r0`](https://pkgs.alpinelinux.org/flag/main/nginx/1.22.0-r0) ([source](https://pkgs.alpinelinux.org/package/edge/main/x86_64/nginx))
* `mariadb`: https://github.com/patzm/dockerfiles/blob/f21a04b8b10a3758b883df203d66b6a83a3f6da0/nextcloud/docker-compose.yml#L4-L5

**Comment by patzm** [comment]
I manually turned off the maintenance mode by running:
```bash
bash-5.1# occ maintenance:mode --off
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode disabled
```

When I then refreshed the Web UI, I could click a button to start the update. Is that expected?

**Comment by ChristophWurst** [comment]
anything in your logs?

**Comment by patzm** [comment]
with warning, error, and fatal filters enabled, I have those logs just before and after the update
![image](https://user-images.githubusercontent.com/5219726/171666496-61413393-9566-4b00-8a74-59a80720c39b.png)
The update was just before 2022-06-02 14:32:31.

The details of the relevant message are:
```
[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: System is in maintenance mode. at <<closure>>

0. /var/www/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   OCA\DAV\Connector\Sabre\MaintenancePlugin->checkMaintenanceMode()
1. /var/www/3rdparty/sabre/dav/lib/DAV/Server.php line 456
   Sabre\DAV\Server->emit()
2. /var/www/3rdparty/sabre/dav/lib/DAV/Server.php line 253
   Sabre\DAV\Server->invokeMethod()
3. /var/www/3rdparty/sabre/dav/lib/DAV/Server.php line 321
   Sabre\DAV\Server->start()
4. /var/www/apps/dav/lib/Server.php line 352
   Sabre\DAV\Server->exec()
5. /var/www/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
6. /var/www/remote.php line 166
   require_once("/var/www/apps/dav/appinfo/v2/remote.php")

PROPFIND /remote.php/dav/calendars/martin/
from 172.21.0.6 at 2022-06-02T14:32:31+02:00
```

The errors from before are probably the same as https://github.com/nextcloud/server/issues/32394, but I just realized that.

**Comment by patzm** [comment]
The update happened at 2022-06-02 12:04:01. I have three errors:
![image](https://user-images.githubusercontent.com/5219726/171667644-301a08fa-617f-4d86-b631-21f6fc529812.png)

1. last
   ```
   [index] Error: Exception: Class "Horde_Mail_Rfc822_Address" not found in file '/data/userapps/mail/lib/Migration/FixCollectedAddresses.php' line 78 at <<closure>>
  
   0. /var/www/lib/private/AppFramework/App.php line 172
      OC\AppFramework\Http\Dispatcher->dispatch()
   1. /var/www/lib/private/Route/Router.php line 298
      OC\AppFramework\App::main()
   2. /var/www/lib/base.php line 1023
      OC\Route\Router->match()
   3. /var/www/index.php line 36
      OC::handleRequest()
   
   GET /settings/apps/update/mail
   from 172.21.0.6 by martin at 2022-06-02T12:04:01+02:00
   ```
2. 2nd-to-last
   ```
   [PHP] Error: Error: include(): Failed opening '/data/userapps/mail/vendor/composer/../pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php' for inclusion (include_path='/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Crypt_Blowfish:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Date:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Exception:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Idna:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_ListHeaders:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Mail:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_ManageSieve:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Mime:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Nls:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Secret:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Smtp:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Socket_Client:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Stream:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Stream_Filter:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Stream_Wrapper:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Stringprep:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Support:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Text_Filter:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Text_Flowed:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Translation:/data/userapps/mail/vendor/pear-pear.horde.org/Horde_Util:/var/www/3rdparty/pear/archive_tar:/var/www/3rdparty/pear/console_getopt:/var/www/3rdparty/pear/pear-core-minimal/src:/var/www/3rdparty/pear/pear_exception:/var/www/apps:/data/userapps') at /var/www/lib/composer/composer/ClassLoader.php#571 at <<closure>>

    0. /var/www/lib/composer/composer/ClassLoader.php line 571
       OC\Log\ErrorHandler::onError()
    1. /var/www/lib/composer/composer/ClassLoader.php line 571
       include()
    2. /var/www/lib/composer/composer/ClassLoader.php line 428
       Composer\Autoload\includeFile()
    3. /data/userapps/mail/lib/Migration/FixCollectedAddresses.php line 78
       Composer\Autoload\ClassLoader->loadClass()
    4. /data/userapps/mail/lib/Migration/FixCollectedAddresses.php line 59
       OCA\Mail\Migration\FixCollectedAddresses->fixAddress()
    5. /var/www/lib/private/Repair.php line 124
       OCA\Mail\Migration\FixCollectedAddresses->run()
    6. /var/www/lib/private/legacy/OC_App.php line 1082
       OC\Repair->run()
    7. /var/www/lib/private/legacy/OC_App.php line 1024
       OC_App::executeRepairSteps()
    8. /var/www/lib/private/Installer.php line 201
       OC_App::updateApp("*** sensitive parameters replaced ***")
    9. /var/www/apps/settings/lib/Controller/AppSettingsController.php line 535
       OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
   10. /var/www/lib/private/AppFramework/Http/Dispatcher.php line 225
       OCA\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
   11. /var/www/lib/private/AppFramework/Http/Dispatcher.php line 133
       OC\AppFramework\Http\Dispatcher->executeController()
   12. /var/www/lib/private/AppFramework/App.php line 172
       OC\AppFramework\Http\Dispatcher->dispatch()
   13. /var/www/lib/private/Route/Router.php line 298
       OC\AppFramework\App::main()
   14. /var/www/lib/base.php line 1023
       OC\Route\Router->match()
   15. /var/www/index.php line 36
       OC::handleRequest()
   
   GET /settings/apps/update/mail
   from 172.21.0.6 by martin at 2022-06-02T12:04:01+02:00
   ```
3. first
   ```
   [PHP] Error: Error: include(/data/userapps/mail/vendor/composer/../pear-pear.horde.org/Horde_Mail/Horde/Mail/Rfc822/Address.php): Failed to open stream: No such file or directory at /var/www/lib/composer/composer/ClassLoader.php#571 at <<closure>>
  
    0. /var/www/lib/composer/composer/ClassLoader.php line 571
       OC\Log\ErrorHandler::onError()
    1. /var/www/lib/composer/composer/ClassLoader.php line 571
       include()
    2. /var/www/lib/composer/composer/ClassLoader.php line 428
       Composer\Autoload\includeFile()
    3. /data/userapps/mail/lib/Migration/FixCollectedAddresses.php line 78
       Composer\Autoload\ClassLoader->loadClass()
    4. /data/userapps/mail/lib/Migration/FixCollectedAddresses.php line 59
       OCA\Mail\Migration\FixCollectedAddresses->fixAddress()
    5. /var/www/lib/private/Repair.php line 124
       OCA\Mail\Migration\FixCollectedAddresses->run()
    6. /var/www/lib/private/legacy/OC_App.php line 1082
       OC\Repair->run()
    7. /var/www/lib/private/legacy/OC_App.php line 1024
       OC_App::executeRepairSteps()
    8. /var/www/lib/private/Installer.php line 201
       OC_App::updateApp("*** sensitive parameters replaced ***")
    9. /var/www/apps/settings/lib/Controller/AppSettingsController.php line 535
       OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
   10. /var/www/lib/private/AppFramework/Http/Dispatcher.php line 225
       OCA\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
   11. /var/www/lib/private/AppFramework/Http/Dispatcher.php line 133
       OC\AppFramework\Http\Dispatcher->executeController()
   12. /var/www/lib/private/AppFramework/App.php line 172
       OC\AppFramework\Http\Dispatcher->dispatch()
   13. /var/www/lib/private/Route/Router.php line 298
       OC\AppFramework\App::main()
   14. /var/www/lib/base.php line 1023
       OC\Route\Router->match()
   15. /var/www/index.php line 36
       OC::handleRequest()
   
   GET /settings/apps/update/mail
   from 172.21.0.6 by martin at 2022-06-02T12:04:01+02:00
   ```

**Comment by patzm** [comment]
Actually, might the `js/maintenance.js` error from above (https://github.com/nextcloud/mail/issues/6630#issuecomment-1145007381) actually be related to ✉️ after all?
https://github.com/nextcloud/server/issues/32394

```
{"reqId":"4ZVteVoMdwwshsthGAj5","level":3,"time":"2022-06-02 12:05:39","remoteAddr":"172.21.0.6","user":"--","app":"jsresourceloader","method":"GET","url":"/settings/apps/update/mail","message":"Could not find resource js/maintenance.js to load","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0","version":"24.0.0.12"}
```

**Comment by resendegu** [comment]
I updated mail to version 1.13.0 and after a while this message appeared (it's in Portuguese - Brazil, but it basically says to Start Update for the Mail app). But when I click to start the update, I get the same behavior of @patzm 
![image](https://user-images.githubusercontent.com/62570230/171752846-f5753f2e-0e83-476c-bfe5-89fd4a44f2db.png)

Then I go to config file and set the maintence to false, but it goes back to the same screen.

I am running Nextcloud in a Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1021-oracle aarch64) with PHP version 8.0-fpm, MariaDB.

**Comment by ChristophWurst** [comment]
> [index] Error: Exception: Class "Horde_Mail_Rfc822_Address" not found in file '/data/userapps/mail/lib/Migration/FixCollectedAddresses.php' line 78 at <<closure>>

That sounds like a bad migration condition.

This class is now found at a different path, but composer will cache the class map from the *previous* version.

Yet once your `apps/mail/appinfo/info.xml` says version v1.13.0 you should be able to proceed with the upgrade.

So it will fail once, but should run through the second time, right?

@resendegu what does your log say? Same `Horde_Mail_Rfc822_Address` inclusion error or something else?

**Comment by steglicd** [comment]
Same issue here, after upgrade:

```
# occ app:update --all
mail new version available: 1.13.0
An unhandled exception has been thrown:
Error: Call to undefined method OC\DB\SchemaWrapper::getDatabasePlatform() in /var/www/html/custom_apps/mail/lib/Migration/Version1130Date20220412111833.php:122
Stack trace:
#0 /var/www/html/lib/private/DB/MigrationService.php(532): OCA\Mail\Migration\Version1130Date20220412111833->changeSchema(Object(OC\Migration\SimpleOutput), Object(Closure), Array)
#1 /var/www/html/lib/private/DB/MigrationService.php(425): OC\DB\MigrationService->executeStep('1130Date2022041...', false)
#2 /var/www/html/lib/private/legacy/OC_App.php(1010): OC\DB\MigrationService->migrate()
#3 /var/www/html/lib/private/Installer.php(200): OC_App::updateApp('mail')
#4 /var/www/html/core/Command/App/Update.php(115): OC\Installer->updateAppstoreApp('mail', false)
#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Update->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Update), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/console.php(99): OC\Console\Application->run()
#11 /var/www/html/occ(11): require_once('/var/www/html/c...')
#12 {main}please check https://nextcloud.tld for issues
```
Then GUI was stuck in maintenance mode and only way to recover was:
```
# occ maintenance:mode --off
# occ app:remove mail
```

**Comment by ChristophWurst** [comment]
> Call to undefined method OC\DB\SchemaWrapper::getDatabasePlatform()

This is a new one! I'll have a look.

**Comment by ChristophWurst** [comment]
What version of Nextcloud do you use @steglicd

**Comment by steglicd** [comment]
@ChristophWurst sorry, I thought maybe because it's also related to migration and also happens from 1.12.1 to 1.13.0 it is related to this ticket. I'm using 22.2.3

**Comment by ChristophWurst** [comment]
Right. `\OCP\DB\ISchemaWrapper::getDatabasePlatform` was added for 23.

**Comment by ChristophWurst** [comment]
Regression of https://github.com/nextcloud/mail/pull/6489.

**Comment by ChristophWurst** [comment]
@kesselb will you have a look?
