### ISSUE TITLE
OCP\AppFramework\QueryException: Could not resolve appName! Class appName does not exist

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/mail#698]
### Steps to reproduce
1. Open the mail app.

### Expected behaviour
No errors should be thrown.

### Actual behaviour
"OCP\AppFramework\QueryException: Could not resolve appName! Class appName does not exist"
Errors in the nextcloud log.

### Mail app

**Mail app version:** 0.7.7

## Server configuration detail

**Operating system:** Linux 4.4.0-108-generic #131-Ubuntu SMP Sun Jan 7 14:34:49 UTC 2018 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mariadb 10.2.12

**PHP version:** 7.1.12-3+ubuntu16.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from older Versions.

**Where did you install Nextcloud from:** nextcloud.com

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.1
 - announcementcenter: 3.1.1
 - apporder: 0.4.1
 - audioplayer: 2.2.2
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - caniupdate: 0.1.1
 - checksum: 0.3.5
 - circles: 0.13.6
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - deck: 0.2.8
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.5
 - files_automatedtagging: 1.2.2
 - files_downloadactivity: 1.1.1
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxedit: 0.0.7
 - gpxpod: 2.2.2
 - groupfolders: 1.1.0
 - issuetemplate: 0.3.0
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.7
 - metadata: 0.6.0
 - nextcloud_announcements: 1.1
 - notes: 2.3.2
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - previewgenerator: 1.0.9
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.1
 - ransomware_protection: 1.0.5
 - richdocuments: 1.12.39
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.2
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

##### Server log (data/nextcloud.log)
<details>
```
{"reqId":"mPRIDWm9djc99aLGcjKv","level":3,"time":"2018-01-10T07:07:03+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxxxxxxxxx","app":"index","method":"GET","url":"\/index.php\/apps\/mail\/api\/avatars\/url\/birgit.weisshand%40gns-mbh.com","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve appName! Class appName does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('appName')\\n#1 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('appName')\\n#2 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(66): OC\\\\ServerContainer->query('appName')\\n#3 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(96): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#4 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#5 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#6 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(416): OC\\\\ServerContainer->query('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#7 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(101): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('OCA\\\\\\\\Mail\\\\\\\\Contro...')\\n#8 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Mail\\\\\\\\Contro...', 'url', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/api\\\/...')\\n#12 \\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/nc_01\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":102}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
```
</details>

**Comment by ChristophWurst** [comment]
Dup of #697 

Thanks for reporting!
