### ISSUE TITLE
Adding a link to message or signature doesn't work

### ISSUE THREAD

**Issue by LostinSpacetime** [nextcloud/mail#7641]
### Steps to reproduce

1. Compose a new email.
2. Write the name of the link.
3. Add link by shortcut ctrls+k or from the UI.
4. Type the address.

### Expected behavior

One is able to write the address.

### Actual behavior

Instead of writing the address in the address field, one writes the address as text in the message and the link is consequently not created.

### Mail app version

2.1.1

### Mailserver or service

SMTP

### Operating system

Ubuntu 18.04

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

The same thing happens when trying to add a link to a signature.

**Comment by GretaD** [comment]
Hello,

so, you cannot add/paste the link in the field below:
![Screenshot from 2022-11-21 11-15-57](https://user-images.githubusercontent.com/12728974/203025131-f97ebcf1-9752-48d3-8264-36193d809baa.png)

this is the problem you are reporting, right? 

Can you please check your webconsole if you have any error when you try to paste the link?

**Comment by LostinSpacetime** [comment]
Yes, this is the problem. This is the output on the console when I click in the field (Chromium without any extensions):

ckeditorerror.js:105 Uncaught TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at u.value (linkui.js:588:37)
    at a.o (linkui.js:494:40)
    at a.value (emittermixin.js:154:47)
    at a.value (editorui.js:159:8)
    at f.<anonymous> (editorui.js:128:76)
    at f.value (emittermixin.js:154:47)
    at w (bubblingemittermixin.js:130:5)
    at u.value (bubblingemittermixin.js:69:32)
    at a.<anonymous> (view.js:185:27)
value @ ckeditorerror.js:105
value @ emittermixin.js:184
value @ editorui.js:159
(anonymous) @ editorui.js:128
value @ emittermixin.js:154
w @ bubblingemittermixin.js:130
value @ bubblingemittermixin.js:69
(anonymous) @ view.js:185
value @ emittermixin.js:154
value @ view.js:436
value @ view.js:614
(anonymous) @ editingcontroller.js:76
value @ emittermixin.js:154
value @ model.js:905
value @ model.js:245
u @ injectunsafekeystrokeshandling.js:125
s @ injectunsafekeystrokeshandling.js:94
(anonymous) @ injectunsafekeystrokeshandling.js:31
value @ emittermixin.js:154
w @ bubblingemittermixin.js:130
value @ bubblingemittermixin.js:69
value @ domeventobserver.js:72
value @ keyobserver.js:33
(anonymous) @ domeventobserver.js:56
value @ emittermixin.js:154
n @ emittermixin.js:244

**Comment by LostinSpacetime** [comment]
In Firefox I get this message in the console:

jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.

**Comment by GretaD** [comment]
ok, i can reproduce it, is a problem with ckeditor5. I will try to debug it and see a solution soon

**Comment by LostinSpacetime** [comment]
Bug is still present in 2.2.1.

**Comment by handkerchief333** [comment]
Are there any news about this issue? In this state, the whole mail functionality is useless for me, because I'm not able to set 1 link to my mails. It's not only the signatures, also the normal mail text. 

In my case, sometimes the link pop up is not showing. Sometimes it appears but I cannot type anything in it, because the text cursor is always fixed to the mail text field in the top left. In Firefox and in Chrome.

**Comment by configonfi** [comment]
Same Problem here (Mail 3.1.1). Small Issue, but large impact.

**Comment by alexanderdd** [comment]
Here in the last post https://help.nextcloud.com/t/mail-app-einbetten-eines-url-links-in-nachrichtentext-funktioniert-nicht-mehr/161205/4 a user reports that this is fixed, maybe someone can confirm and close this issue?

**Comment by LostinSpacetime** [comment]
The issue is not resolved entirely. While it's now possible to add a link to a signature or message, editing the link is not possible with a similar behavior. (unresponsive text field)

**Comment by VieuFou34** [comment]
Hi,
 I get the same problem with Mail 3.7.8 Nextcloud 29.0.6.

Plus the text format of the signature doesn't shows in the messages.

Thx

**Comment by msegec** [comment]
As above, same issue in Firefox.

**Comment by msegec** [comment]
As above, same issue in Firefox.
