### ISSUE TITLE
Server error on sending from unified inbox

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/mail#8]
Nothing in the server or Nextcloud log. JS console:
```
jquery.js:8630 POST http://localhorst/nextcloud/index.php/apps/mail/accounts/1/send 500 (Internal Server Error)
```

```
Type: Horde_Imap_Client_Exception
Code: 200
Message: Could not open mailbox "all-inboxes".
File: /home/jan/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Socket.php
Line: 1239
```

Trace
```
#0 /home/jan/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php(1044): Horde_Imap_Client_Socket->_openMailbox(Object(Horde_Imap_Client_Mailbox), 1)
#1 /home/jan/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php(2504): Horde_Imap_Client_Base->openMailbox(Object(Horde_Imap_Client_Mailbox), 1)
#2 /home/jan/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client/Horde/Imap/Client/Base.php(2471): Horde_Imap_Client_Base->_fetchWrapper(Object(Horde_Imap_Client_Mailbox), Object(Horde_Imap_Client_Fetch_Query), Array)
#3 /home/jan/nextcloud/apps/mail/lib/model/imapmessage.php(363): Horde_Imap_Client_Base->fetch(Object(Horde_Imap_Client_Mailbox), Object(Horde_Imap_Client_Fetch_Query), Array)
#4 /home/jan/nextcloud/apps/mail/lib/model/imapmessage.php(74): OCA\Mail\Model\IMAPMessage->loadMessageBodies()
#5 /home/jan/nextcloud/apps/mail/lib/mailbox.php(196): OCA\Mail\Model\IMAPMessage->__construct(Object(Horde_Imap_Client_Socket), Object(Horde_Imap_Client_Mailbox), 'WzEsMTU3ODdd', NULL, false)
#6 /home/jan/nextcloud/apps/mail/lib/controller/accountscontroller.php(291): OCA\Mail\Mailbox->getMessage('WzEsMTU3ODdd')
#7 [internal function]: OCA\Mail\Controller\AccountsController->send(1, 'YWxsLWluYm94ZXM...', NULL, 'Messagetext bla...', '"Name bla...', '', '', 3791, 'WzEsMTU3ODdd', NULL, '')
#8 /home/jan/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)
#9 /home/jan/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(90): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\AccountsController), 'send')
#10 /home/jan/nextcloud/lib/private/AppFramework/App.php(117): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\AccountsController), 'send')
#11 /home/jan/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Mail\\Contro...', 'send', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#12 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#13 /home/jan/nextcloud/lib/private/Route/Router.php(298): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#14 /home/jan/nextcloud/lib/base.php(969): OC\Route\Router->match('/apps/mail/acco...')
#15 /home/jan/nextcloud/index.php(48): OC::handleRequest()
#16 {main}
```

**Comment by ChristophWurst** [comment]
> http://localhorst/nextcloud/index.php/apps/mail/accounts/1/send

Please share which parameters the client sends to the server

**Comment by jancborchardt** [comment]
Request
```
URL:http://localhorst/nextcloud/index.php/apps/mail/accounts/3/send
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:127.0.0.1:80
```
Response Headers
```
Cache-Control:no-store, no-cache, must-revalidate
Connection:close
Content-Security-Policy:default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
Content-Type:text/html; charset=UTF-8
Date:Mon, 29 Aug 2016 12:00:30 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:no-cache
Server:Apache/2.4.18 (Ubuntu)
Transfer-Encoding:chunked
X-Content-Type-Options:nosniff
X-Download-Options:noopen
X-Frame-Options:SAMEORIGIN
X-Permitted-Cross-Domain-Policies:none
X-Robots-Tag:none
X-XSS-Protection:1; mode=block
```
Request Headers
```
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:2518
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:oc_sessionPassphrase=4HmnNq8jCKIR0%2FlONx7iCAX8vprdNQM5PXJWfxPNC1MKhdt%2Fyr1aZPCmuL%2Fqo3%2BsOqLARdVyBt6Y1PaE5J%2F0m61THArzxwwuKuosjFHndx0KcctO%2Fxa51urXQaRG8ept; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; oc41b2kazncz=0lgi4e34lodqkqc5p4ldeg03c0
Host:localhorst
OCS-APIREQUEST:true
Origin:http://localhorst
requesttoken:NBYiXixXKHJnLRgLESYAFiYrPTZsUy0qAWU/ViMCNVk=:STZmfgzA0ujZkv7tkJWsXdteW0YeZfd7Hu/uD/Yw7Bg=
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36
X-Requested-With:XMLHttpRequest
Form Data
view source
view URL encoded
to:"Person" <example@yolo.com>
cc:bla@example.com
bcc:
body: Body text
folderId:YWxsLWluYm94ZXM=
messageId:WzMsOTQ1XQ==
draftUID:1005
aliasId:
```
(Is this the info you mean?)

**Comment by jancborchardt** [comment]
Ah yeah, using Chrome.
