### ISSUE TITLE
Hotkey to move email to archive and open next email does not work

### ISSUE THREAD

**Issue by basilweibel** [nextcloud/mail#8047]
### Is your feature request related to a problem? Please describe.

Right now it is very slow to process your emails in nextcloud mail because you cannot archive emails with a hotkey.

### Describe the solution you'd like

Implement a hotkey e.g. a or e which can be used when viewing an email to move that email to the archive and open the next email. Gmail uses e as a hotkey to archive and I would suggest to follow that convention.

### Additional context

```
TypeError: _this6.onArchive is not a function
    at _callee6$ (Mailbox.vue:378:1)
    at tryCatch (Mailbox.vue:50:1)
    at Generator.<anonymous> (Mailbox.vue:50:1)
    at Generator.next (Mailbox.vue:50:1)
    at asyncGeneratorStep (Mailbox.vue:50:1)
    at _next (Mailbox.vue:50:1)
    at Mailbox.vue:50:1
    at new Promise (<anonymous>)
    at Mailbox.vue:50:1
    at VueComponent.handleShortcut (Mailbox.vue:418:1)
```

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/mail/pull/7991

The shortcut is `a`. 
We forgot to update the documentation.
