### ISSUE TITLE
Horde_Smtp_Exception: Message size exceeds fixed limit

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8295]
### Steps to reproduce

1. ???

### Expected behavior

Message is sent

### Actual behavior

```
Horde_Smtp_Exception: Message size exceeds fixed limit
#14 /mail/vendor/nextcloud/horde-smtp/lib/Horde/Smtp.php(1076): Horde_Smtp::_getResponse
#13 /mail/vendor/nextcloud/horde-smtp/lib/Horde/Smtp.php(659): Horde_Smtp::send
#12 /mail/vendor/bytestream/horde-mail/lib/Horde/Mail/Transport/Smtphorde.php(143): Horde_Mail_Transport_Smtphorde::send
#11 /mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Part.php(1620): Horde_Mime_Part::send
#10 /mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Mail.php(479): Horde_Mime_Mail::send
#9 /mail/lib/Service/MailTransmission.php(272): OCA\Mail\Service\MailTransmission::sendMessage
#8 /mail/lib/Service/MailTransmission.php(344): OCA\Mail\Service\MailTransmission::sendLocalMessage
#7 /mail/lib/Service/OutboxService.php(142): OCA\Mail\Service\OutboxService::sendMessage
#6 /mail/lib/Controller/OutboxController.php(227): OCA\Mail\Controller\OutboxController::send
#5 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\App::main
#2 /var/www/cloud.domain.com/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/cloud.domain.com/nextcloud/lib/base.php(1052): OC::handleRequest
#0 /var/www/cloud.domain.com/nextcloud/index.php(36): null

Horde_Mail_Exception: Message size exceeds fixed limit
#12 /mail/vendor/bytestream/horde-mail/lib/Horde/Mail/Transport/Smtphorde.php(145): Horde_Mail_Transport_Smtphorde::send
#11 /mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Part.php(1620): Horde_Mime_Part::send
#10 /mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Mail.php(479): Horde_Mime_Mail::send
#9 /mail/lib/Service/MailTransmission.php(272): OCA\Mail\Service\MailTransmission::sendMessage
#8 /mail/lib/Service/MailTransmission.php(344): OCA\Mail\Service\MailTransmission::sendLocalMessage
#7 /mail/lib/Service/OutboxService.php(142): OCA\Mail\Service\OutboxService::sendMessage
#6 /mail/lib/Controller/OutboxController.php(227): OCA\Mail\Controller\OutboxController::send
#5 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\App::main
#2 /var/www/cloud.domain.com/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/cloud.domain.com/nextcloud/lib/base.php(1052): OC::handleRequest
#0 /var/www/cloud.domain.com/nextcloud/index.php(36): null

Horde_Mime_Exception: Message size exceeds fixed limit
#11 /mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Part.php(1642): Horde_Mime_Part::send
#10 /mail/vendor/bytestream/horde-mime/lib/Horde/Mime/Mail.php(479): Horde_Mime_Mail::send
#9 /mail/lib/Service/MailTransmission.php(272): OCA\Mail\Service\MailTransmission::sendMessage
#8 /mail/lib/Service/MailTransmission.php(344): OCA\Mail\Service\MailTransmission::sendLocalMessage
#7 /mail/lib/Service/OutboxService.php(142): OCA\Mail\Service\OutboxService::sendMessage
#6 /mail/lib/Controller/OutboxController.php(227): OCA\Mail\Controller\OutboxController::send
#5 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\App::main
#2 /var/www/cloud.domain.com/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/cloud.domain.com/nextcloud/lib/base.php(1052): OC::handleRequest
#0 /var/www/cloud.domain.com/nextcloud/index.php(36): null

OCA\Mail\Exception\ServiceException: Could not send message: Message size exceeds fixed limit
#9 /mail/lib/Service/MailTransmission.php(274): OCA\Mail\Service\MailTransmission::sendMessage
#8 /mail/lib/Service/MailTransmission.php(344): OCA\Mail\Service\MailTransmission::sendLocalMessage
#7 /mail/lib/Service/OutboxService.php(142): OCA\Mail\Service\OutboxService::sendMessage
#6 /mail/lib/Controller/OutboxController.php(227): OCA\Mail\Controller\OutboxController::send
#5 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/cloud.domain.com/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\App::main
#2 /var/www/cloud.domain.com/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/cloud.domain.com/nextcloud/lib/base.php(1052): OC::handleRequest
#0 /var/www/cloud.domain.com/nextcloud/index.php(36): null
```

### Mail app version

3.0.0

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
The same attachment can be sent from Thunderbird.

**Comment by ChristophWurst** [comment]
Thunderbird

![20230324_103532](https://user-images.githubusercontent.com/1374172/227482382-997b1f4c-b424-4663-8bc8-cf10c8dc0c02.png)

Gnome Evolution

![Bildschirmfoto vom 2023-03-24 10-34-01](https://user-images.githubusercontent.com/1374172/227482432-ff02bf48-b34b-4815-be46-d01b48f88ce2.png)

**Comment by corvus-albus** [comment]
For over a week now, we face the "Message size exceeds fixed limit" error. As an admin, I have no chance to find out, who's responsible. The username is not included in the log. The user himself likely hasn't noticed at sending time, that his E-Mail wasn't send. Otherwise he would have take action. If he recognizes afterwards, that his email wasn't send, he will blame the mail-app being unreliable. 
Because I don't know the username, I can't give a hint to the user in question. 
Now the situation is: an unsure user and a log filled with errors.
Perhaps it is a good idea to include the username in the error log until this issue is closed.

**Comment by p4p4j0hn** [comment]
@corvus-albus were you able to find out the issue? My log is spammed by this as well.
