### ISSUE TITLE
autodetect account fails to operate, "error connecting to mail server" despite works for other users

### ISSUE THREAD

**Issue by blizzz** [nextcloud/mail#836]
### Steps to reproduce
1. Be @skjnldsv on our company instance
2. open mail app

### Expected behaviour

Auto-detected email settings should work as does with all of us others

### Actual behaviour

"Error connecting to mail server" and a Horde exception. Same when manually editing the config.

### Mail app

**Mail app version:** 0.7.10

**Mailserver or service:** Dovecot & Postfix

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL 5.7

**PHP version:** 7.0

**Version:** 13.0.1

**Updated from an older version or fresh install:** updated

#### Client configuration
**Browser:** Safari

##### Web server error log
```

```

##### Server log (data/nextcloud.log)
<details>
```
{"reqId":"speX0W53wnbSBmdxfnqA","level":1,"time":"2018-03-20T10:40:29+00:00","remoteAddr":"213.152.161.74","user":"anonymizedUserId","app":"mail","method":"PUT","url":"\/apps\/mail\/api\/accounts\/-2","message":"setting up auto detected account","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.162 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"speX0W53wnbSBmdxfnqA","level":1,"time":"2018-03-20T10:40:39+00:00","remoteAddr":"213.152.161.74","user":"anonymizedUserId","app":"mail","method":"PUT","url":"\/apps\/mail\/api\/accounts\/-2","message":"Test-Account-Failed: anonymizedUserId, mx.nextcloud.com, 143, anonymizedUserId, ssl -> Error connecting to mail server.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.162 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"speX0W53wnbSBmdxfnqA","level":1,"time":"2018-03-20T10:40:39+00:00","remoteAddr":"213.152.161.74","user":"anonymizedUserId","app":"mail","method":"PUT","url":"\/apps\/mail\/api\/accounts\/-2","message":"Test-Account-Failed: anonymizedUserId, mx.nextcloud.com, 143, anonymizedUserId@nextcloud.com, ssl -> Error connecting to mail server.","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.162 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"speX0W53wnbSBmdxfnqA","level":3,"time":"2018-03-20T10:40:39+00:00","remoteAddr":"213.152.161.74","user":"anonymizedUserId","app":"PHP","method":"PUT","url":"\/apps\/mail\/api\/accounts\/-2","message":"Creating default object from empty value at \/var\/www\/html\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php#4375","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.162 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"speX0W53wnbSBmdxfnqA","level":3,"time":"2018-03-20T10:40:39+00:00","remoteAddr":"213.152.161.74","user":"anonymizedUserId","app":"index","method":"PUT","url":"\/apps\/mail\/api\/accounts\/-2","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method stdClass::write()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4283): Horde_Imap_Client_Socket->_processCmd(Object(Horde_Imap_Client_Interaction_Pipeline), Object(Horde_Imap_Client_Interaction_Command), Object(Horde_Imap_Client_Interaction_Command))\\n#1 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4230): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(846): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(512): Horde_Imap_Client_Socket->_tryLogin(*** sensitive parameters replaced ***)\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(833): Horde_Imap_Client_Socket->_login(*** sensitive parameters replaced ***)\\n#5 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Account.php(160): Horde_Imap_Client_Base->login(*** sensitive parameters replaced ***)\\n#6 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Service\\\/AutoConfig\\\/ImapConnector.php(81): OCA\\\\Mail\\\\Account->getImapConnection()\\n#7 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Service\\\/AutoConfig\\\/ImapConnectivityTester.php(84): OCA\\\\Mail\\\\Service\\\\AutoConfig\\\\ImapConnector->connect('anonymizedUserId@next...', '5709f80b6a67b89...', 'Barthelemy Bria...', 'mx.nextcloud.co...', 143, 'tls', 'anonymizedUserId')\\n#8 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Service\\\/AutoConfig\\\/ImapServerDetector.php(61): OCA\\\\Mail\\\\Service\\\\AutoConfig\\\\ImapConnectivityTester->test('anonymizedUserId@next...', 'mx.nextcloud.co...', Array, 'password...', 'Barthelemy Bria...')\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Service\\\/AutoConfig\\\/ConfigurationDetector.php(53): OCA\\\\Mail\\\\Service\\\\AutoConfig\\\\ImapServerDetector->detect('anonymizedUserId@next...', 'password...', 'Barthelemy Bria...')\\n#10 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Service\\\/AutoConfig\\\/AutoConfig.php(55): OCA\\\\Mail\\\\Service\\\\AutoConfig\\\\ConfigurationDetector->detectImapAndSmtp('anonymizedUserId@next...', 'password...', 'Barthelemy Bria...')\\n#11 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Service\\\/SetupService.php(72): OCA\\\\Mail\\\\Service\\\\AutoConfig\\\\AutoConfig->createAutoDetected('anonymizedUserId@next...', 'password...', 'Barthelemy Bria...')\\n#12 \\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/lib\\\/Controller\\\/AccountsController.php(151): OCA\\\\Mail\\\\Service\\\\SetupService->createNewAutoConfiguredAccount('Barthelemy Bria...', 'anonymizedUserId@next...', 'password...')\\n#13 [internal function]: OCA\\\\Mail\\\\Controller\\\\AccountsController->update(-2, 'Barthelemy Bria...', 'anonymizedUserId@next...', 'password...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true)\\n#14 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'update')\\n#16 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\AccountsController), 'update')\\n#17 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Mail\\\\\\\\Contro...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#20 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/api\\\/...')\\n#21 \\\/var\\\/www\\\/html\\\/index.php(37): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4429}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.162 Safari\/537.36","version":"13.0.1.1"}
```
</details>

##### IMAP log (data/horde_imap.log)

n/a

</details>

##### SMTP log (data/horde_smtp.log)

n/a

@ChristophWurst

**Comment by blizzz** [comment]
never mind
