### ISSUE TITLE
Mail body for this mail(12345) could not be loaded

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8400]
### Steps to reproduce

1. ??

### Expected behavior

No error

### Actual behavior

```
OCP\AppFramework\Db\DoesNotExistException: Mail body for this mail(11704) could not be loaded
#15 /mail/lib/IMAP/ImapMessageFetcher.php(442): OCA\Mail\IMAP\ImapMessageFetcher::loadBodyData
#14 /mail/lib/IMAP/ImapMessageFetcher.php(395): OCA\Mail\IMAP\ImapMessageFetcher::handleTextMessage
#13 /mail/lib/IMAP/ImapMessageFetcher.php(346): OCA\Mail\IMAP\ImapMessageFetcher::getPart
#12 /mail/lib/IMAP/ImapMessageFetcher.php(206): OCA\Mail\IMAP\ImapMessageFetcher::fetchMessage
#11 /mail/lib/IMAP/MessageMapper.php(297): OCA\Mail\IMAP\MessageMapper::OCA\Mail\IMAP\{closure}
#10 [internal](0): array_map
#9 /mail/lib/IMAP/MessageMapper.php(298): OCA\Mail\IMAP\MessageMapper::findByIds
#8 /mail/lib/IMAP/MessageMapper.php(84): OCA\Mail\IMAP\MessageMapper::find
#7 /mail/lib/Service/MailManager.php(194): OCA\Mail\Service\MailManager::getImapMessage
#6 /mail/lib/Controller/MessagesController.php(220): OCA\Mail\Controller\MessagesController::getBody
#5 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\App::main
#2 /var/www/cloud.nextcloud.com/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/cloud.nextcloud.com/nextcloud/lib/base.php(1056): OC::handleRequest
#0 /var/www/cloud.nextcloud.com/nextcloud/index.php(36): null

OCA\Mail\Exception\ServiceException: Could not load message
#7 /mail/lib/Service/MailManager.php(201): OCA\Mail\Service\MailManager::getImapMessage
#6 /mail/lib/Controller/MessagesController.php(220): OCA\Mail\Controller\MessagesController::getBody
#5 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\App::main
#2 /var/www/cloud.nextcloud.com/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/cloud.nextcloud.com/nextcloud/lib/base.php(1056): OC::handleRequest
#0 /var/www/cloud.nextcloud.com/nextcloud/index.php(36): null
``` 

### Mail app version

3.1.1

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
Not seen again so far -> close
