### ISSUE TITLE
OutboxController::create(): Argument #1 ($accountId) must be of type int, null given

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/mail#8401]
### Steps to reproduce

1. Let @jancborchardt use this app

### Expected behavior

Happy Jan-C

### Actual behavior

```
TypeError: OCA\Mail\Controller\OutboxController::create(): Argument #1 ($accountId) must be of type int, null given, called in /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 230
#6 /mail/lib/Controller/OutboxController.php(105): OCA\Mail\Controller\OutboxController::create
#5 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OC\AppFramework\Http\Dispatcher::executeController
#4 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\App::main
#2 /var/www/cloud.nextcloud.com/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/cloud.nextcloud.com/nextcloud/lib/base.php(1056): OC::handleRequest
#0 /var/www/cloud.nextcloud.com/nextcloud/index.php(36): null

Exception: OCA\Mail\Controller\OutboxController::create(): Argument #1 ($accountId) must be of type int, null given, called in /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 230 in file '/var/www/cloud.nextcloud.com/nextcloud/apps/mail/lib/Controller/OutboxController.php' line 105
#4 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(169): OC\AppFramework\Http\Dispatcher::dispatch
#3 /var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/App.php(183): OC\AppFramework\App::main
#2 /var/www/cloud.nextcloud.com/nextcloud/lib/private/Route/Router.php(315): OC\Route\Router::match
#1 /var/www/cloud.nextcloud.com/nextcloud/lib/base.php(1056): OC::handleRequest
#0 /var/www/cloud.nextcloud.com/nextcloud/index.php(36): null
```

### Mail app version

3.1.1

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
The `accountId` must be missing at https://github.com/nextcloud/mail/blob/v3.1.1/src/components/NewMessageModal.vue#L230-L232

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/commit/30d4c1eb8b8ddbc883a16032fc51e2c9be9e28c3 is the only change we did to that file recently
