### ISSUE TITLE
Cannot download attachement to Nextcloud Files

### ISSUE THREAD

**Issue by martinhankovec** [nextcloud/mail#9645]
### Steps to reproduce

1. Click on "Uložit do Souborů" (Store in Files?) to store attachement in Files on Nextcloud
2. Nothing happens
3. In Javascript Console:
vue.runtime.esm.js:3065 TypeError: (0 , V.a1)(...).setMultiSelect(...).addMimeTypeFilter(...).setModal is not a function
 at o.saveToCloud (MessageAttachment.vue:196:1)
    at click (MessageAttachment.vue:1:1899)
    at an (vue.runtime.esm.js:3033:30)
    at o.n (vue.runtime.esm.js:1832:20)
    at an (vue.runtime.esm.js:3033:30)
    at e.$emit (vue.runtime.esm.js:3732:17)
    at o.onClick (actionText-jLsEBszD.mjs:118:16)
    at o.handleClick (NcActionButton.mjs:113:12)
    at an (vue.runtime.esm.js:3033:30)
    at HTMLButtonElement.n (vue.runtime.esm.js:1832:20)

### Expected behavior

To open window to select target folder on Nextcloud Files

### Actual behavior

Nothing happens

### Mail app version

3.6.0

### Mailserver or service

remote IMAP

### Operating system

Synology

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MariaDB

**Comment by Neokaan** [comment]
i think this is a duplicate from #9632 and #9633

**Comment by martinhankovec** [comment]
Yes, it seems so.
