### ISSUE TITLE
Email signature is not inserted, if locale is German (Germany) for a new user

### ISSUE THREAD

**Issue by bjoernv** [nextcloud/mail#9815]
### Steps to reproduce

1. Create a new user
2. Set locale to German (Germany) for the new user
3. Configure an email signature
4. Start a new private browser window (no cookies!)
5. Login the new user
5. Compose a new message

### Expected behavior

Signature should be inserted in Compose windows

### Actual behavior

No signature is inserted

### Mail app version

3.7.2

### Mailserver or service

Sendmail

### Operating system

Ubuntu Linux 22.04

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database

MySQL

### Additional info

The workaround is to set locale to German (not German (Germany)). Signature works now, even if the locale is switched back to German (Germany).

**Comment by cetcondor** [comment]
Thanks for the workaround. It does help.

**Comment by ChristophWurst** [comment]
I am not able to reproduce (anymore). @bjoernv @cetcondor could you try again with a current release?

If it happens again, please reproduce with the browser console open. Are there any logged errors?

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!

**Comment by feltel** [comment]
We migrated to NC29 this weekend. We had to switch from Roundcube to the native Mail app in the same step. We faced the same issue discussed here. If a user has the locale "de_DE" set than no signature is sent despite being set. If the locale is set to "de" than the mails are sent with added signature.

I can provide further informations as needed.

**Comment by ChristophWurst** [comment]
@feltel please reproduce with the browser console open. Are there any logged errors?

**Comment by feltel** [comment]
[browserconsole.txt](https://github.com/user-attachments/files/18823907/browserconsole.txt)

As someone else mentioned you can set the locale back to de_DE and it still works and inserts the signature. Even if I switch the browser I have an inserted signature. I´ve used a fresh account to reproduce the problem. Attached please find the browser console log.

**Comment by ChristophWurst** [comment]
```
ConsoleLogger.js:74 [ERROR] mail: could not find CKEditor translations for "de-DE" Object
value @ ConsoleLogger.js:74
index.esm.js:76 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at c (index.esm.js:76:51)
    at b (index.esm.js:530:18)
    at focus-trap.esm.js:311:27
    at Array.map (<anonymous>)
    at w (focus-trap.esm.js:310:46)
    at Object.activate (focus-trap.esm.js:816:9)
    at o.useFocusTrap (NcModal.mjs:562:22)
infinite-scroll.js:197 binding <div data-v-40ec28c3 class=​"app-content-list envelope-list" infinite-scroll-immediate-check=​"false" infinite-scroll-distance=​"10" role=​"heading" aria-level=​"2" data-v-7b4bc577>​…​</div>​flex Object e
TextEditor.vue:291 [ERROR] mail: could not find CKEditor translations for "de-DE" {app: 'mail', uid: 'firstname.lastname@bar.baz', level: 0, error: Error: Cannot find module './de-DE'
    at https://cloud.bar.baz/nextcloud/apps/mail/js/mail.535…}
```

^ this seems to be relevant.
